name: c_material
description: >
  A modern Flutter color system that provides predefined colors, semantic color
  tokens, Material 3 themes, and helpful color extensions for building
  consistent and scalable UI designs.

version: 2.2.2

homepage: https://github.com/Ammar2000-Matarieh/colors_package.git

environment:
  sdk: ^3.5.4
  flutter: ">=3.16.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
