name: c_material
description:  A package to show All Colors in Any Application for iOS and Android, support Open from a different resource like Access Eazy Colors.
version: 0.0.5
homepage: https://pub.dev/packages/c_material

environment:
  sdk: ^3.5.4
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0


flutter:
  assets: 
    - assets/images


