name: c_material
description: A package to show All Colors in Any Application for iOS and Android, support Open from a different resource like Access Eazy Colors.
version: 2.1.0
homepage: https://github.com/Ammar2000-Matarieh/colors_package.git

environment:
  sdk: ^3.5.4
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
